# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hyp.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, os, math
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QDialogButtonBox, QVBoxLayout, QLabel
from PyQt5.QtCore import QRegExp, Qt
from PyQt5.QtGui import QRegExpValidator, QDoubleValidator, QKeyEvent, QFont


# Program Designer and Coder  -  Brian Kies

# Program uses standard formulas to compute right hypotenuse length
# using sides, angle, cosine and sine functions

# Function adds correct path for .png images inside executable
def resource_path(relative_path):
        try:
            base_path = sys._MEIPASS
        except Exception:
            base_path = os.path.abspath(".")
        return os.path.join(base_path, relative_path)


# Add triangle image paths
triangle1_path = resource_path("triangle1.png")
triangle2_path = resource_path("triangle2.png")
triangle3_path = resource_path("triangle3.png")
triangle4_path = resource_path("triangle4.png")
# Add text image paths
text1_path = resource_path("text1.png")
text2_path = resource_path("text2.png")
text3_path = resource_path("text3.png")

# Dialog box prevents user from entering angle >= 90° or comma
class warningDlg(QDialog):
    def __init__(self, warningType, parent=None):
        super().__init__(parent)

        self.setStyleSheet("background-color: rgb(75, 75, 75); color: rgb(255, 255, 205);")
        self.setGeometry(600, 400, 200, 100)
        # Remove question mark from title bar
        self.setWindowFlags(self.windowFlags() & ~Qt.WindowType.WindowContextHelpButtonHint)

        wType = warningType
        message = QLabel()
        message.setFont(QFont('Times', 12))

        QBtn = QDialogButtonBox.Ok

        self.buttonBox = QDialogButtonBox(QBtn)
        self.buttonBox.accepted.connect(self.accept)

        layout = QVBoxLayout()
        if wType == 'ang':
            self.setWindowTitle('Angle Restriction')
            message.setText("Angle must be less than 90.0° for calculations.")
        elif wType == 'comma':
            self.setWindowTitle('Invalid Entry')
            message.setText("You may not enter comma for decimal number.")

        layout.addWidget(message)
        layout.addWidget(self.buttonBox)
        self.setLayout(layout)

# Generated from QT Designer UI file
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        width = 860
        height = 670
        MainWindow.setEnabled(True)
        MainWindow.setFixedSize(width, height)
        MainWindow.setStyleSheet("background-color: rgb(75, 75, 75);\n"
                                 "color: rgb(255, 255, 205);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLbl = QtWidgets.QLabel(self.centralwidget)
        self.titleLbl.setGeometry(QtCore.QRect(170, 0, 511, 41))
        # Set basic font for all fields except point size
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        # Point size 14 for main title
        font.setPointSize(14)
        self.titleLbl.setFont(font)
        self.titleLbl.setObjectName("titleLbl")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 240, 420, 310))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        font.setPointSize(10)
        self.twoSidesRB = QtWidgets.QRadioButton(self.groupBox)
        self.twoSidesRB.setGeometry(QtCore.QRect(10, 20, 190, 30))
        self.twoSidesRB.setFont(font)
        self.twoSidesRB.setObjectName("twoSidesRB")
        self.adjSideAngRB = QtWidgets.QRadioButton(self.groupBox)
        self.adjSideAngRB.setGeometry(QtCore.QRect(10, 110, 191, 31))
        self.adjSideAngRB.setFont(font)
        self.adjSideAngRB.setObjectName("adjSideAngRB")
        self.oppSideAngRB = QtWidgets.QRadioButton(self.groupBox)
        self.oppSideAngRB.setGeometry(QtCore.QRect(10, 196, 191, 31))
        self.oppSideAngRB.setFont(font)
        self.oppSideAngRB.setObjectName("oppSideAngRB")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 10, 201, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.xLbl = QtWidgets.QLabel(self.groupBox_2)
        self.xLbl.setGeometry(QtCore.QRect(10, 20, 21, 21))
        self.xLbl.setFont(font)
        self.xLbl.setObjectName("xLbl")
        self.yLbl = QtWidgets.QLabel(self.groupBox_2)
        self.yLbl.setGeometry(QtCore.QRect(110, 20, 21, 21))
        self.yLbl.setFont(font)
        self.yLbl.setObjectName("yLbl")

        # Use validator to allow User to only input decimal numbers for Line Edit fields
        validator = QRegExpValidator(QtCore.QRegExp("\\d+(\\.\\d{1,2})?"))

        self.xSideLE = QtWidgets.QLineEdit(self.groupBox_2)
        self.xSideLE.setEnabled(False)
        self.xSideLE.setGeometry(QtCore.QRect(40, 20, 50, 20))
        self.xSideLE.textChanged.connect(self.onTextChanged)
        self.xSideLE.setValidator(validator)
        self.xSideLE.setFont(font)
        self.xSideLE.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom | QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.xSideLE.setObjectName("xSideLE")
        self.ySideLE = QtWidgets.QLineEdit(self.groupBox_2)
        self.ySideLE.setEnabled(False)
        self.ySideLE.setGeometry(QtCore.QRect(140, 20, 50, 20))
        self.ySideLE.textEdited.connect(self.onTextChanged)
        self.ySideLE.setValidator(validator)
        self.ySideLE.setFont(font)
        self.ySideLE.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom | QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.ySideLE.setObjectName("ySideLE")

        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(210, 100, 201, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.xLbl_2 = QtWidgets.QLabel(self.groupBox_3)
        self.xLbl_2.setGeometry(QtCore.QRect(10, 20, 21, 21))
        self.xLbl_2.setFont(font)
        self.xLbl_2.setObjectName("xLbl_2")
        self.yLbl_2 = QtWidgets.QLabel(self.groupBox_3)
        self.yLbl_2.setGeometry(QtCore.QRect(100, 20, 35, 31))
        self.yLbl_2.setText("")
        self.yLbl_2.setPixmap(QtGui.QPixmap("../Trig_Lesson/angle_equals.png"))
        self.yLbl_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom | QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.yLbl_2.setObjectName("yLbl_2")
        self.adjSideLE = QtWidgets.QLineEdit(self.groupBox_3)
        self.adjSideLE.setEnabled(False)
        self.adjSideLE.setGeometry(QtCore.QRect(40, 20, 50, 20))
        self.adjSideLE.setFont(font)
        self.adjSideLE.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.adjSideLE.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom | QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.adjSideLE.textEdited.connect(self.onTextChanged)
        self.adjSideLE.setValidator(validator)
        self.adjSideLE.setObjectName("adjSideLE")
        self.adjAngLE = QtWidgets.QLineEdit(self.groupBox_3)
        self.adjAngLE.setEnabled(False)
        self.adjAngLE.setGeometry(QtCore.QRect(140, 20, 50, 20))
        self.adjAngLE.setFont(font)
        self.adjAngLE.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom | QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.adjAngLE.textEdited.connect(self.onTextChanged)
        self.adjAngLE.setValidator(validator)
        self.adjAngLE.setObjectName("adjAngLE")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(210, 180, 201, 61))
        self.groupBox_4.setObjectName("groupBox_4")
        self.xLbl_3 = QtWidgets.QLabel(self.groupBox_4)
        self.xLbl_3.setGeometry(QtCore.QRect(10, 20, 21, 21))
        self.xLbl_3.setObjectName("xLbl_3")
        self.yLbl_3 = QtWidgets.QLabel(self.groupBox_4)
        self.yLbl_3.setGeometry(QtCore.QRect(100, 20, 35, 31))
        self.yLbl_3.setText("")
        self.yLbl_3.setPixmap(QtGui.QPixmap("../Trig_Lesson/angle_equals.png"))
        self.yLbl_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom | QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.yLbl_3.setObjectName("yLbl_3")
        self.oppSideLE = QtWidgets.QLineEdit(self.groupBox_4)
        self.oppSideLE.setEnabled(False)
        self.oppSideLE.setGeometry(QtCore.QRect(40, 20, 50, 20))
        self.oppSideLE.setFont(font)
        self.oppSideLE.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom | QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.oppSideLE.textEdited.connect(self.onTextChanged)
        self.oppSideLE.setValidator(validator)
        self.oppSideLE.setObjectName("oppSideLE")
        self.oppAngLE = QtWidgets.QLineEdit(self.groupBox_4)
        self.oppAngLE.setEnabled(False)
        self.oppAngLE.setGeometry(QtCore.QRect(140, 20, 50, 20))
        self.oppAngLE.setFont(font)
        self.oppAngLE.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.oppAngLE.textEdited.connect(self.onTextChanged)
        self.oppAngLE.setValidator(validator)
        self.oppAngLE.setObjectName("oppAngLE")
        self.calculateBtn = QtWidgets.QPushButton(self.groupBox)
        self.calculateBtn.setGeometry(QtCore.QRect(210, 260, 75, 25))
        self.calculateBtn.setObjectName("calculateBtn")
        self.calculateBtn.setEnabled(False)
        self.calculateBtn.setStyleSheet("QPushButton:disabled { color: gray; background-color: lightgray;}")
        self.clearBtn = QtWidgets.QPushButton(self.groupBox)
        self.clearBtn.setGeometry(QtCore.QRect(340, 260, 75, 25))
        self.clearBtn.setObjectName("clearBtn")
        self.triangle1Lbl_1 = QtWidgets.QLabel(self.centralwidget)
        self.triangle1Lbl_1.setGeometry(QtCore.QRect(0, 60, 220, 150))
        self.triangle1Lbl_1.setFrameShape(QtWidgets.QFrame.Box)
        self.triangle1Lbl_1.setText("")
    #    self.triangle1Lbl_1.setPixmap(QtGui.QPixmap("../HYP/triangle1.png"))
        self.triangle1Lbl_1.setPixmap(QtGui.QPixmap(triangle1_path))
        self.triangle1Lbl_1.setObjectName("triangle1Lbl_1")
        self.triangle1Lbl_2 = QtWidgets.QLabel(self.centralwidget)
        self.triangle1Lbl_2.setGeometry(QtCore.QRect(220, 60, 220, 150))
        self.triangle1Lbl_2.setStyleSheet("")
        self.triangle1Lbl_2.setFrameShape(QtWidgets.QFrame.Box)
        self.triangle1Lbl_2.setText("")
        self.triangle1Lbl_2.setPixmap(QtGui.QPixmap(triangle2_path))
        self.triangle1Lbl_2.setObjectName("triangle1Lbl_2")
        self.triangle1Lbl_3 = QtWidgets.QLabel(self.centralwidget)
        self.triangle1Lbl_3.setGeometry(QtCore.QRect(440, 60, 210, 150))
        self.triangle1Lbl_3.setFrameShape(QtWidgets.QFrame.Box)
        self.triangle1Lbl_3.setText("")
        self.triangle1Lbl_3.setPixmap(QtGui.QPixmap(triangle3_path))
        self.triangle1Lbl_3.setObjectName("triangle1Lbl_3")
        self.triangle1Lbl_4 = QtWidgets.QLabel(self.centralwidget)
        self.triangle1Lbl_4.setGeometry(QtCore.QRect(650, 60, 210, 150))
        self.triangle1Lbl_4.setFrameShape(QtWidgets.QFrame.Box)
        self.triangle1Lbl_4.setText("")
        self.triangle1Lbl_4.setPixmap(QtGui.QPixmap(triangle4_path))
        self.triangle1Lbl_4.setObjectName("triangle1Lbl_4")
        self.resultLbl = QtWidgets.QLabel(self.centralwidget)
        self.resultLbl.setGeometry(QtCore.QRect(150, 590, 61, 31))
        font.setPointSize(14)
        self.resultLbl.setFont(font)
        self.resultLbl.setObjectName("resultLbl")
        self.resultLE = QtWidgets.QLineEdit(self.centralwidget)
        self.resultLE.setGeometry(QtCore.QRect(220, 590, 520, 30))
   #     font = QtGui.QFont()
        font.setPointSize(11)
        self.resultLE.setFont(font)
        self.resultLE.setAlignment(QtCore.Qt.AlignmentFlag.AlignVCenter|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.resultLE.setObjectName("resultLE")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(550, 270, 201, 41))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(text1_path))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(485, 360, 360, 30))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(text2_path))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(500, 440, 311, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(text3_path))
        self.label_3.setObjectName("label_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 40, 841, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(10, 220, 831, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(10, 560, 841, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        # Connections to QRadioButtons
        # User selects two sides, adjacent side and angle, or opposite side and angle
        # to calculate hypotenuse of right triangle
        self.twoSidesRB.clicked.connect(self.EnableSidesEntry)
        self.adjSideAngRB.clicked.connect(self.EnableAdjSideAngEntry)
        self.oppSideAngRB.clicked.connect(self.EnabelOppSideAngEntry)
        # Calculate Button connects to UserSelection
        self.calculateBtn.clicked.connect(self.UserSelection)
        self.clearBtn.clicked.connect((self.ClearAll))
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Function will enable Calculate button once both fields have data entered
        # using two sides, adjacent side and angle, or opposite side and angle
    def onTextChanged(self):
        if self.xSideLE.text() != "" and self.ySideLE.text() != "":
            self.calculateBtn.setEnabled(True)
        elif self.adjSideLE.text() != "" and self.adjAngLE.text() != "":
            self.calculateBtn.setEnabled(True)
        elif self.oppSideLE.text() != "" and self.oppAngLE.text() != "":
            self.calculateBtn.setEnabled(True)

        # Uses standard ratio formula ( π / 180 = radians / degrees ) to convert degrees to rads

    def ConvertToRads(self, ang):
        rads = ang * math.pi / 180
        return rads

        # clears text from other two Line Edits

    def ClearAll(self):
        self.xSideLE.clear()
        self.ySideLE.clear()
        self.adjSideLE.clear()
        self.adjAngLE.clear()
        self.oppSideLE.clear()
        self.oppAngLE.clear()
        self.resultLE.clear()
        self.twoSidesRB.setChecked(False)
        self.adjSideAngRB.setChecked(False)
        self.oppSideAngRB.setChecked(False)
        self.calculateBtn.setEnabled(False)
    #    self.calculateBtn.setStyleSheet("QPushButton:disabled { color: gray; background-color: lightgray;}")

    def ClearEntries(self):
        global userChoice

        match userChoice:
            case 'sides':
                self.adjSideLE.clear()
                self.adjSideLE.setEnabled(False)
                self.adjAngLE.clear()
                self.adjAngLE.setEnabled(False)
                self.oppSideLE.clear()
                self.oppSideLE.setEnabled(False)
                self.oppAngLE.clear()
                self.oppAngLE.setEnabled(False)
            case 'adj':
                self.xSideLE.clear()
                self.xSideLE.setEnabled(False)
                self.ySideLE.clear()
                self.ySideLE.setEnabled(False)
                self.oppSideLE.clear()
                self.oppSideLE.setEnabled(False)
                self.oppAngLE.clear()
                self.oppAngLE.setEnabled(False)
            case 'opp':
                self.xSideLE.clear()
                self.xSideLE.setEnabled(False)
                self.ySideLE.clear()
                self.ySideLE.setEnabled(False)
                self.adjSideLE.clear()
                self.adjSideLE.setEnabled(False)
                self.adjAngLE.clear()
                self.adjAngLE.setEnabled(False)

        # Connected to Radio Button for two sides

    def EnableSidesEntry(self):
        global userChoice
        # Set global userChoice to 'sides' for match-case statement in UserSelection function
        userChoice = 'sides'
        self.calculateBtn.setEnabled(False)
        self.xSideLE.setEnabled(True)
        self.xSideLE.setFocus()
        self.ySideLE.setEnabled(True)
        self.ClearEntries()

        # Connected to Radio Button for adjacent side and angle

    def EnableAdjSideAngEntry(self):
        global userChoice
        # Set userChoice to 'adj' for match-case statement in UserSelection function
        userChoice = 'adj'
        self.calculateBtn.setEnabled(False)
        self.adjSideLE.setEnabled(True)
        self.adjSideLE.setFocus()
        self.adjAngLE.setEnabled(True)
        self.ClearEntries()

        # Connected to Radio Button for opposite side and angle

    def EnabelOppSideAngEntry(self):
        global userChoice
        # Set userChoice to 'opp' for match-case statement in UserSelection function
        userChoice = 'opp'
        self.calculateBtn.setEnabled(False)
        self.oppSideLE.setEnabled(True)
        self.oppSideLE.setFocus()
        self.oppAngLE.setEnabled(True)
        self.ClearEntries()

        # UserSelection uses global variable userChoice
        # to determine which function will calculate hypotenuse length

    def UserSelection(self):
        global userChoice

        match userChoice:
            case 'sides':
                self.CalculateTwoSides()
            case 'adj':
                self.CalculateAdjSideAndAngle()
            case 'opp':
                self.CalculateOppSideAndAngle()

        # calculate hypotenuse using two sides

    def CalculateTwoSides(self):
        if (self.xSideLE.text() == '' or self.ySideLE.text == ''):
            return None
        else:
            xStr = self.xSideLE.text()
            if xStr == '':
                return None
            else:
                # Convert x to float
                x = float(xStr)

            yStr = self.ySideLE.text()
            if yStr == '':
                return None
            else:
                # Convert y to float
                y = float(yStr)

        x = float(self.xSideLE.text())
        y = float(self.ySideLE.text())
        hyp = math.sqrt(x * x + y * y)
        self.resultLE.setText(f'  Hypotenuse for sides {x:.2f} and {y:.2f} is {hyp:.2f}.')

        # calculate hypotenuse using adjacent side and angle

    def CalculateAdjSideAndAngle(self):
        if (self.adjSideLE.text == '' or self.adjAngLE.text == ''):
            return None
        else:
            adjStr = self.adjSideLE.text()
            if adjStr == '':
                return None
            else:
                # Convert adjacent side to float
                adj = float(adjStr)

            angStr = float(self.adjAngLE.text())
            if angStr == '':
                return None
            else:
                # Convert adjacent angle to float
                ang = float(angStr)

        # Check for angle size - must be less than 90.0°
        if ang >= 90.0:
            dlg = warningDlg('ang')
            dlg.exec()
            self.adjAngLE.clear()
            self.adjAngLE.setFocus()
            self.calculateBtn.setEnabled(False)
            return None

        adj = float(self.adjSideLE.text())
        ang = float(self.adjAngLE.text())
        angInRads = self.ConvertToRads(ang)
        hyp = adj / math.cos(angInRads)
        self.resultLE.setText(f'  Hypotenuse for adjacent side {adj:.2f} and angle {ang:.2f}° is {hyp:.2f}.')

        # calculate hypotenuse using opposite side and angle

    def CalculateOppSideAndAngle(self):
        if (self.oppSideLE.text == '' or self.oppAngLE.text == ''):
            return None
        else:
            oppStr = self.oppSideLE.text()
            if oppStr == '':
                return None
            else:
                # Convert opposite side to float
                opp = float(oppStr)

        angStr = float(self.oppAngLE.text())
        if angStr == '':
            return None
        else:
            # Convert adjacent angle to float
            ang = float(angStr)

        # Check for angle size - must be less than 90.0°
        if (ang >= 90.0):
            dlg = warningDlg('ang')
            dlg.exec()
            self.oppAngLE.clear()
            self.oppAngLE.setFocus()
            self.calculateBtn.setEnabled(False)
            return None

        opp = float(self.oppSideLE.text())
        ang = float(self.oppAngLE.text())
        angInRads = self.ConvertToRads(ang)
        hyp = opp / math.sin(angInRads)
        self.resultLE.setText(f'  Hypotenuse for opposite side {opp:.2f} and angle {ang:.2f}° is {hyp:.2f}.')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Trig Lesson"))
        self.titleLbl.setText(_translate("MainWindow", "Find Hypotenuse Using Two Sides Or With Side And Angle"))
        self.twoSidesRB.setText(_translate("MainWindow", "Use Two Sides"))
        self.adjSideAngRB.setText(_translate("MainWindow", "Use Adjacent Side And Angle"))
        self.xLbl.setText(_translate("MainWindow", "X  = "))
        self.yLbl.setText(_translate("MainWindow", "Y  = "))
        self.oppSideAngRB.setText(_translate("MainWindow", "Use Opposite Side And Angle"))
        self.xLbl_2.setText(_translate("MainWindow", "X  = "))
        self.xLbl_3.setText(_translate("MainWindow", "Y  = "))
        self.calculateBtn.setText(_translate("MainWindow", "Calculate"))
        self.clearBtn.setText(_translate("MainWindow", "Clear"))
        self.resultLbl.setText(_translate("MainWindow", "Result:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
